# Generated by Django 4.0.2 on 2022-02-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0002_meal_slug_variety_slug_alter_meal_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='variety',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
