# Generated by Django 4.0.2 on 2022-02-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0003_alter_meal_slug_alter_variety_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='variety',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
