# Generated by Django 4.0.2 on 2022-02-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0006_alter_meal_discount_alter_meal_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
