# Generated by Django 4.0.2 on 2022-02-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0009_alter_contact_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='remark',
            field=models.TextField(default='a'),
        ),
    ]
