# Generated by Django 4.0.2 on 2022-02-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0010_contact_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='remark',
            field=models.TextField(),
        ),
    ]
