# Generated by Django 4.0.2 on 2022-02-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0011_alter_contact_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
