# Generated by Django 4.0.2 on 2022-02-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0015_paidorder_shopcart_shipping_paidorder_shopcart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paidorder',
            options={'managed': True, 'verbose_name': 'PaidOrder', 'verbose_name_plural': 'PaidOrders'},
        ),
        migrations.AlterModelOptions(
            name='shipping',
            options={'managed': True, 'verbose_name': 'Shipping', 'verbose_name_plural': 'Shippings'},
        ),
        migrations.AlterModelOptions(
            name='shopcart',
            options={'managed': True, 'verbose_name': 'ShopCart', 'verbose_name_plural': 'ShopCarts'},
        ),
        migrations.AlterModelTable(
            name='paidorder',
            table='paidorder',
        ),
        migrations.AlterModelTable(
            name='shipping',
            table='shipping',
        ),
        migrations.AlterModelTable(
            name='shopcart',
            table='shopcart',
        ),
    ]
