# Generated by Django 4.0.2 on 2022-02-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
