# Generated by Django 4.0.2 on 2022-03-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_profile_cart_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
