# Generated by Django 4.0.2 on 2022-02-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0002_shopcart_how_spicey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='how_spicey',
            field=models.CharField(max_length=100),
        ),
    ]
