# Generated by Django 4.0.2 on 2022-02-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0003_alter_shopcart_how_spicey'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='amount',
            field=models.IntegerField(default=2),
        ),
    ]
