# Generated by Django 4.0.2 on 2022-02-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0005_remove_shopcart_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='spicy',
        ),
    ]
