# Generated by Django 4.0.2 on 2022-02-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0007_shopcart_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='amount',
        ),
    ]
