# Generated by Django 4.0.2 on 2022-02-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0010_alter_shopcart_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
