# Generated by Django 4.0.2 on 2022-02-28 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0011_alter_shopcart_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='amount',
        ),
    ]
