# Generated by Django 4.0.2 on 2022-03-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0012_remove_shopcart_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='spice',
        ),
        migrations.AlterField(
            model_name='shipping',
            name='admin_remark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('pending', 'pending'), ('processing', 'processing'), ('shipping', 'shipping'), ('delivered', 'delivered')], default='new', max_length=50, null=True),
        ),
    ]
