# Generated by Django 4.0.2 on 2022-03-10 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0015_shipping_paidorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaidOrder',
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
